# Generated by Django 4.1.7 on 2023-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0006_addvisitor_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvisitor',
            name='remark',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
