# Generated by Django 4.2.3 on 2024-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0009_addvisitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvisitor',
            name='status',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
