# Generated by Django 4.2.3 on 2024-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0011_alter_addvisitor_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvisitor',
            name='department',
        ),
        migrations.AddField(
            model_name='addvisitor',
            name='apartmentno',
            field=models.CharField(default='True', max_length=150),
        ),
        migrations.AddField(
            model_name='addvisitor',
            name='category',
            field=models.CharField(default='True', max_length=150),
        ),
        migrations.AddField(
            model_name='addvisitor',
            name='floororwings',
            field=models.CharField(default='True', max_length=150),
        ),
    ]
