# Generated by Django 4.2.3 on 2024-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avsapp', '0012_remove_addvisitor_department_addvisitor_apartmentno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='True', max_length=150)),
                ('visname', models.CharField(max_length=200)),
                ('mobilenumber', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=15)),
                ('apartment', models.CharField(default='True', max_length=150)),
                ('floor', models.CharField(default='True', max_length=150)),
                ('inputdate', models.CharField(max_length=250)),
                ('todate', models.CharField(max_length=250)),
                ('passdescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
